### PR TITLE
Added initial version of the Zram Swap init script.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by dkati** [comment]
Did u test it? And if so, how?

**Comment by slaff** [comment]
> Did u test it? And if so, how?

Not yet fully tested but seems to make the UI so much smoother. Will report later this week or the next one.

**Comment by dkati** [comment]
How u know that Zram is mounted.?

**Comment by slaff** [comment]
> How u know that Zram is mounted.?

You can check if the zram module is loaded by the presence of `/sys/block/zram0` directory.
For the zram support you will need a [boot.img with zram support](https://github.com/JDCTeam/android_vendor_jdc/files/12767765/boot-zram.zip). 

If present you can create a swap partition with zram and mount it using the zram_swap script included in this PR.

But I am having a problem -  no matter what I try the zram_swap service is not started and not even found. 

The files are present:
```
ls -lha /system/vendor/etc/init/hw/init.jdcteam.rc
-rw-r--r-- 1 root root 369 2009-01-01 01:00 /system/vendor/etc/init/hw/init.jdcteam.rc

ls -lha /system/vendor/bin/zram_swap
-rwxr-xr-x 1 root shell 1.0K 2009-01-01 01:00 /system/vendor/bin/zram_swap
```

But trying to start the service even manually errors with missing service.
```
dmesg -c
start zram_swap
dmesg
# [ 3242.028869] init: Control message: Could not find 'zram_swap' for ctl.start from pid: 19925 (start zram_swap)

I tried also this one:

 # start emmc_trim
Unable to start service 'emmc_trim'
See dmesg for error reason.
```

Any idea why I cannot start run the commands on boot?

**Pull request merged**
